#!/bin/bash -e

############################################################################
# Monitor system memory every second.  Useful for profiling processes

echo "      date     time $(free -m | grep total | sed -E 's/^    (.*)/\1/g')"
while true; do
    echo "$(date '+%Y-%m-%d %H:%M:%S') $(free -h | grep Mem: | sed 's/Mem://g')"
    sleep 1
done

